website/movie/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$',views.movie,name="movie"),
	
]

website/musico/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [

	url(r'^list/$',views.music,name="musico"),
	url(r'^(?P<pk>[0-9]+)/$',views.listsong,name="list_song"),
	url(r'^settings/$',views.add_movie,name="setting"),
	url(r'^add-song/$',views.add_song,name="add_song"),
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^movie/',include('movie.urls')),
    url(r'^userauth/',include('userauth.urls')),
    url(r'^home/',TemplateView.as_view(template_name='userauth/home.html')),
    url(r'^music/',include('musico.urls')),

]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/musico/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
# Create your models here.


class movielist(models.Model):
    name = models.CharField(max_length=200)
    about = models.CharField(max_length=200)
    image = models.FileField(upload_to='pictures/')
    date = models.DateField()
    upload_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.name

class song(models.Model):
    album = models.ForeignKey( movielist, on_delete=models.CASCADE )
    song_name = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    song_location = models.FileField(upload_to="")

    def __str__(self):
        return self.song_name

website/musico/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class MovieForm(forms.ModelForm):

    class Meta:
        model = models.movielist
        fields = ('name', 'about', 'date', 'image')


class SongForm(forms.ModelForm):

    class Meta:
        model = models.song
        fields = ('album', 'song_name', 'artist', 'song_location')

website/musico/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import generic
from . import models
from django.shortcuts import render
from django.http import HttpResponse
from . import forms
# Create your views here.

def music(request):
    if request.user.is_authenticated:
        movies = models.movielist.objects.all()
        return render(request, 'musico/home.html', {'movie_list': movies})
    else:
        return HttpResponse("you need to login to access song")

def listsong(request, pk):
    if request.user.is_authenticated:
        movie = models.movielist.objects.get(pk=pk)
        return render(request, 'musico/list.html',{'album':movie})
    else:
        return HttpResponse("you need to login to access song")

def add_movie(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.MovieForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return HttpResponse("movie saved")
        else:
            form = forms.MovieForm()
        return render(request, 'musico/setting.html', {'form': form})
    else:
        return HttpResponse("you need to login to access song")

def add_song(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = forms.SongForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return HttpResponse("song saved")
        else:
            form = forms.SongForm()
        return render(request, 'musico/songsave.html', {'form': form})
    else:
        return HttpResponse("you need to login to access song")

website/musico/templates/musico/home.html
{% extends 'musico/nav.html' %}

{% block content %}
<div class="container">
  <br>
<h2>List of movie or albums :</h2>
<div class="row">
{% for album in movie_list %}
<div class="col-md-4">
<div class="card" style="width:350px;margin:10px;">
    <img class="card-img-top" src="{{ album.image.url }}/" alt="{{album.name}} image" style="width:100%;height:300px;">
    <div class="card-body">
      <h4 class="card-title">{{album.name}}</h4>
      <a href="/music/{{album.id}}/" class="btn btn-primary">Songs</a>
    </div>
  </div>
  </div>
{% endfor %}
</div>
</div>

{% endblock %}
ss

website/musico/templates/musico/list.html
{% extends 'musico/nav.html' %}

{% block content %}

<div class="container">
  <br>
<h2>Movie details:</h2>
<div class="row">
<div class="col-md-12">
<div class="card" style="margin:10px;">
    <img class="card-img-top" src="{{ album.image.url }}" alt="{{album.name}} image" style="width:100%;">
    <div class="card-body">
      <h4 class="card-title">Details:</h4>
      <p class="card-text"><b>Name:</b> {{ album.name }}</p>
      <p class="card-text"><b>about:</b> {{ album.about }}</p>
      <p class="card-text"><b>date of upload:</b> {{ album.upload_date }}</p>
        <h4 class="card-title">Songs:</h4>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Song name</th>
                <th>Artist</th>
                <th>play it</th>
              </tr>
            </thead>
            <tbody>
            {% for song in album.song_set.all %}
            <tr>
              <td> {{song.song_name}} </td>
              <td> {{song.artist}} </td>
              <td> <audio controls>
                    <source src="{{song.song_location.url}}" type="audio/mp3">
                  </audio>
                 </td>
           </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
  </div>
  </div>
</div>
</div>


{% endblock %}

website/musico/templates/musico/nav.html
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

    <a class="navbar-brand" href="/music/list/">Albums</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/music/settings">Add album</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/music/add-song">Add song</a>
      </li>
    </ul>
    <ul class="navbar-nav  ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/userauth/logout">Logout</a>
      </li>
    </ul>
  </nav>

{% block content %}
{% endblock %}
</body>
</html>

website/musico/templates/musico/setting.html
{% extends 'musico/nav.html' %}{% block content %}
<div class="container">
 <h1>Add albums: </h1>
   <div class="row" style="margin:20px;">
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Upload</button>
</form>
</div>
</div>
{% endblock %}

website/musico/templates/musico/songsave.html
{% block content %}
<div class="container">
   <h1>Add songs : </h1>
 <div class="row" style="margin:20px;">
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save song</button>
</form>
</div>
</div>
{% endblock %}